### ISSUE TITLE
I am not able to make post request in postman

### ISSUE THREAD

**Issue by UmeshYakkundi** [gugui3z24/MEAN-Stack-With-Angular-2-Tutorial#1]
I have followed your youtube.com  video tutorials and did my project as I had seen in video but its not working for me and also attaching destination below,
[https://github.com/UmeshYakkundi/MEAN-Stack-App.git](url)

**Comment by gugui3z24** [comment]
I do not see any posts requests in your application. You should have a folder called "routes" which has all of the backend HTTP requests. But your application is working fine.

**Comment by SureshkumarVenkatachalam** [comment]
Hi David,
I'm learning the MEAN stack by following your videos and facing an **issue while trying to test the API**'s Registration method using Postman. i.e. before installing the body-parser i just tried to test API to confirm whether it sends "hello world" but it throws "**Cannot POST /authentication/register**".
Please suggest.
